// src/lib/game/types.ts
// Pure type definitions for the client game state. No runtime imports.
import type { Faction } from "@/lib/units";
import type { GiftBoxId } from "@/lib/constants/gifts";
import type { ExplosionColor } from "@/lib/constants";
import type { HybridCommanderAbilityId } from "@/lib/constants/war-mode";

export type WarTargetType = "nation" | "player";

export interface Cell {
  id: number;
  faction: Faction | "hybrid" | "target";
  tier: number;
  /** Visual unit line within the tier (0–2). Same variant required to merge. */
  variant?: number;
  parentDogId?: number;
  parentCatId?: number;
  isHybrid?: boolean;
  seed?: string;
  imageUrl?: string;
  /** War Mode: is this unit currently deployed off-board? */
  deployedUntil?: number;

  // Live Target fields
  isTarget?: boolean;
  targetType?: WarTargetType;
  targetId?: string;
  targetLabel?: string;
}

export interface HybridNFT {
  id: number;
  seed: string;
  parentDogId: number;
  parentCatId: number;
  createdAt: number;
  minted: boolean;
  imagePrompt: string;
  imageUrl?: string;
}

export interface PendingHybrid {
  id: number;
  parentDogId: number;
  parentCatId: number;
  from: number;
  to: number;
}

export interface WarTarget {
  id: string;
  type: WarTargetType;
  /** For nation targets */
  nationId?: string;
  nationName?: string;
  /** For player targets */
  playerId?: number;
  playerName?: string;
  /** Board index where it currently sits */
  boardIndex: number;
  spawnedAt: number;
  expiresAt: number;
}

export interface WarModeState {
  active: boolean;
  startedAt: number;
  endsAt: number;
  /** 0 = fully dog controlled, 100 = fully cat controlled, 50 = contested center */
  frontLine: number;
  /** Total control generated by this player in the current session */
  controlGenerated: number;
  /** Last time passive control was applied */
  lastPassiveAt: number;
  /** Active hybrid commander abilities */
  activeAbilities: {
    id: HybridCommanderAbilityId;
    endsAt: number;
  }[];
  /** Personal cooldown until next War Mode */
  cooldownUntil: number;
  /** Extreme win (front ≤5 or ≥95) */
  victory?: boolean;
  /** Any session just finished — drives the end modal */
  sessionComplete?: boolean;
  /** Energy spent this session (entry + deploys + merges) */
  energySpent?: number;
  /** Snapshot of rewards granted on end (for the modal) */
  lastRewards?: {
    glory: number;
    wardog: number;
    warcat: number;
    energyRefund: number;
  };

  // Live Targets
  targets: WarTarget[];
  mergesSinceLastTarget: number;
  hasSeenTargetTutorial: boolean;
}

export interface GameState {
  board: (Cell | null)[];
  nextId: number;
  glory: number;
  energy: number;
  lastRegenAt: number;
  totalMerges: number;
  highestTier: number;
  lastDailyClaim: number;
  dailyStreak: number;
  wardogTokens: number;
  warcatTokens: number;
  referralCode: string;
  referrals: any[];
  invitedBy?: string;
  hasSeenTutorial: boolean;
  gloryBoostUntil: number;
  lastSeenAt: number;
  pendingIdleReward: any | null;
  nukesUsedToday: number;
  lastNukeDay: number;
  pendingHybrid: PendingHybrid | null;
  hybrids: HybridNFT[];

  explosion: {
    idx: number;
    color: ExplosionColor;
    key: number;
  } | null;

  lastMergeAt?: number;
  comboCount?: number;
  achievements?: string[];

  nukesOwned?: number;
  nukesLaunchedToday?: number;
  totalNukesLaunched?: number;
  isTerrorist?: boolean;
  lastNukeTargetId?: number | null;

  /** Inventory of unopened gift boxes */
  giftBoxes?: Partial<Record<GiftBoxId, number>>;

  // Daily / tasks (kept for compatibility)
  tasks?: any[];
  dailyQuests?: any[];
  dailyQuestsDate?: number;

  // Board Conquer system
  dogSideConquered: boolean;
  catSideConquered: boolean;

  // WAR MODE
  warMode: WarModeState;
}

export interface MergeResult {
  ok: boolean;
  token?: "wardog" | "warcat";
  amount?: number;
  isHybrid?: boolean;
  combo?: number;
  comboMult?: number;
  unlocked?: string[];
  gloryGained?: number;
  variantPerfect?: boolean;
}

export interface Task {
  id: string;
  title?: string;
  desc?: string;
  done?: boolean;
  claimed?: boolean;
  progress?: number;
  target?: number;
  [key: string]: any;
}

export interface DailyQuest {
  id: string;
  title: string;
  desc: string;
  target: number;
  progress: number;
  claimed: boolean;
  reward?: number;
  wardog?: number;
  warcat?: number;
  energy?: number;
  [key: string]: any;
}

export interface Referral {
  id?: string;
  code?: string;
  [key: string]: any;
}

export interface IdleReward {
  glory?: number;
  energy?: number;
  tokens?: number;
  [key: string]: any;
}
