/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEconomyRouteImport } from './routes/admin/economy'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminNationsRouteImport } from './routes/admin/nations'
import { Route as AdminToolsRouteImport } from './routes/admin/tools'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicTelegramLoginRouteImport } from './routes/api/public/telegram/login'
import { Route as ApiPublicTelegramTickRouteImport } from './routes/api/public/telegram/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEconomyRoute = AdminEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNationsRoute = AdminNationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramLoginRoute = ApiPublicTelegramLoginRouteImport.update({
  id: '/api/public/telegram/login',
  path: '/api/public/telegram/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramTickRoute = ApiPublicTelegramTickRouteImport.update({
  id: '/api/public/telegram/tick',
  path: '/api/public/telegram/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nations': typeof AdminNationsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telegram/login': typeof ApiPublicTelegramLoginRoute
  '/api/public/telegram/tick': typeof ApiPublicTelegramTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nations': typeof AdminNationsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telegram/login': typeof ApiPublicTelegramLoginRoute
  '/api/public/telegram/tick': typeof ApiPublicTelegramTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/nations': typeof AdminNationsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telegram/login': typeof ApiPublicTelegramLoginRoute
  '/api/public/telegram/tick': typeof ApiPublicTelegramTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/admin/economy'
    | '/admin/logs'
    | '/admin/nations'
    | '/admin/tools'
    | '/admin/users'
    | '/admin/'
    | '/api/public/health'
    | '/api/public/telegram/login'
    | '/api/public/telegram/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/economy'
    | '/admin/logs'
    | '/admin/nations'
    | '/admin/tools'
    | '/admin/users'
    | '/admin'
    | '/api/public/health'
    | '/api/public/telegram/login'
    | '/api/public/telegram/tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/admin/economy'
    | '/admin/logs'
    | '/admin/nations'
    | '/admin/tools'
    | '/admin/users'
    | '/admin/'
    | '/api/public/health'
    | '/api/public/telegram/login'
    | '/api/public/telegram/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicTelegramLoginRoute: typeof ApiPublicTelegramLoginRoute
  ApiPublicTelegramTickRoute: typeof ApiPublicTelegramTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/economy': {
      id: '/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AdminEconomyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nations': {
      id: '/admin/nations'
      path: '/nations'
      fullPath: '/admin/nations'
      preLoaderRoute: typeof AdminNationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/login': {
      id: '/api/public/telegram/login'
      path: '/api/public/telegram/login'
      fullPath: '/api/public/telegram/login'
      preLoaderRoute: typeof ApiPublicTelegramLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/tick': {
      id: '/api/public/telegram/tick'
      path: '/api/public/telegram/tick'
      fullPath: '/api/public/telegram/tick'
      preLoaderRoute: typeof ApiPublicTelegramTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEconomyRoute: typeof AdminEconomyRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNationsRoute: typeof AdminNationsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEconomyRoute: AdminEconomyRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNationsRoute: AdminNationsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicTelegramLoginRoute: ApiPublicTelegramLoginRoute,
  ApiPublicTelegramTickRoute: ApiPublicTelegramTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
